# Generated by Django 3.1.2 on 2020-11-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfilepath',
            name='filepath',
            field=models.TextField(max_length=1000),
        ),
    ]
