# Generated by Django 3.1.2 on 2020-11-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20201115_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('width', models.SmallIntegerField(verbose_name='Ширина')),
                ('num', models.SmallIntegerField(verbose_name='Порядковый номер')),
            ],
            options={'verbose_name': 'Колонка таблицы', 'verbose_name_plural': 'Колонки таблицы'},
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.AlterField(
            model_name='csvfilepath',
            name='filepath',
            field=models.TextField(max_length=1000, verbose_name='Путь к файлу'),
        ),
    ]
