# Generated by Django 3.1.2 on 2020-11-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20201116_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablecolumn',
            options={'ordering': ('num',), 'verbose_name': 'Колонка таблицы', 'verbose_name_plural': 'Колонки таблицы'},
        ),
        migrations.AlterField(
            model_name='csvfilepath',
            name='filepath',
            field=models.FilePathField(max_length=1000, verbose_name='Путь к файлу'),
        ),
    ]
