# Generated by Django 3.1.2 on 2020-11-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_auto_20201116_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvfilepath',
            options={'verbose_name': 'csv-файл', 'verbose_name_plural': 'csv-файлы'},
        ),
        migrations.AlterField(
            model_name='csvfilepath',
            name='filepath',
            field=models.FilePathField(max_length=200, verbose_name='Путь к файлу'),
        ),
    ]
