# Generated by Django 3.1.2 on 2020-11-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_auto_20201116_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfilepath',
            name='filepath',
            field=models.FileField(upload_to=''),
        ),
    ]
